spring:
  datasource:
    url: jdbc:postgresql://wallet-db:5432/walletdb
    username: walletuser
    password: walletpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true